### ISSUE TITLE
Documentation on Parallel Render addon usage.

### ISSUE THREAD

**Issue by mond-cz** [elmopl/ktba#1]
I can see a progress bar that ends in 100% http://pasteall.org/pic/index.php?id=118260
Running from Terminal ends with http://pasteall.org/pic/index.php?id=118261
... but there is not any output (video) file on my iMac (OS X 10.11.6) with official 2.78c or today downloaded buildboot of 2.79.

Also does exist any detailed description of addon? I understood number of "instances" should goes to number of cores (for 2 core processor should it be set 2, right?), but what I don't understand is the rest system, probably because I don't see the result - "Number of batches". What batch means in this case. Thanks for more details.

**Comment by elmopl** [comment]
Output should be where the standard "Properties" -> "Output" configuration path points to.
The script essentially just launches "Maximum number of instances" of Blender in background and renders your sequence in parts.

I have just added wiki page about [addons](https://github.com/elmopl/ktba/wiki/Addons).
Hopefully this will answer the second part of your questions too.

Let me know if anything needs to be clarified on wiki and I'll try my best to do that.

**Comment by mond-cz** [comment]
Thanks for wiki :) It seems I got it.

From your answer about output issue I understand that script works fine for you.
Is there any thread that I can ask community if someone with mac has this problem too?
My output directory is set as usual - double slash "//" to save file in blend directory.

**Comment by elmopl** [comment]
Oh, yes, that would be it. I never knew you could put relative path as output.
I had to work around the fact there might be some unsaved changes to project and yet when starting new instances of Blender I had to provide them with project file. Using last save might not give the result you'd expect. So I ended up saving current state in temporary file and pass that onto those instances.
And with relative path configured you probably got all output in temporary directory that this temporary project file went to.

I will look into this. I might change the script to save temporary project file in the same directory as your last saved one.

> BTW on wiki you wrote "image output formats could also work ...", but when I want to bring script, instead of config window, warning message appear something like - "image is not supported, only movie format"

Has been so long I don't remember what I've done there.
I removed that comment from wiki. If there will be voices it might be useful I might look into this, but I think issue was that there is no generic way to work out image filenames.

**Comment by elmopl** [comment]
Going to close this one as documentation is there. For other things separate issues were created.
