### ISSUE TITLE
Change internal state variable from string to enum (to avoid bugs)

### ISSUE THREAD

**Issue by tin2tin** [elmopl/ktba#10]
Saving the .blend and do a succesful render and then adding a space character to the filepath, without saving the .blend gives this error in the latter part of the render session:
![image](https://user-images.githubusercontent.com/1322593/44960166-02b15300-aefb-11e8-8bf7-5b12bd55ac56.png)

(It seems like the same moment in the render process the error comes as exporting in AVI RAW?)

**Comment by elmopl** [comment]
Quick fix. It was a stupid mistake (I set state to "Cleaning up", but in other place it expected it to be "Cleaning" and it failed to find it which crashed it.
That only crashed if your cleaning up timed up with attempt to make an update to status bar (i.e. only if at the time of updating status bar it was in "cleaning" state it would fail, so it might not have been easily reproducible).

**Comment by tin2tin** [comment]
I'm still getting red lines in the header concerning cleaning. Maybe a stupid question(i'm not a coder) but it says:
`537            'Clean': ('INFO', 'Cleaning Up'),`

Should it be 'Clean' instead of 'Cleaning'? in `519` ?

**Comment by elmopl** [comment]
It should. Same stupid mistake.

Although this time at least it shouldn't have failed/stopped abruptly. 

I will fix it properly (use an `enum` instead of strings) later on.

**Comment by tin2tin** [comment]
Great. This may be a small fix, but it feels so much more stable now. :-)
