### ISSUE TITLE
Preferences Are Missing for Parallel Render

### ISSUE THREAD

**Issue by eplipswich** [elmopl/ktba#14]
![image](https://user-images.githubusercontent.com/37729199/48298801-7f197100-e4fe-11e8-92c4-86ae92433438.png)

I installed the Parallel Render addon, but the preferences aren't showing for me.

Also, the render setup isn't showing for me either (the window after pressing space and typing parallel render). It just leads to this:

![image](https://user-images.githubusercontent.com/37729199/48298817-c1db4900-e4fe-11e8-9caf-63699033c5e9.png)

Am I missing something??

**Comment by elmopl** [comment]
Everything above seems to actually work correctly.
I think confusion comes from the fact I haven't had a chance to update wiki article on how to use it and it shows old UI features.

I have just updated wiki.
Options have all moved to "properties" panel and are saved on per project basis.

**Comment by elmopl** [comment]
Wiki is updated, so it should all be good now.
