### ISSUE TITLE
Parallel Render

### ISSUE THREAD

**Issue by tin2tin** [elmopl/ktba#19]
Are you going to update your great Parallel Render script? :-)

**Comment by elmopl** [comment]
Done in #21

**Comment by tin2tin** [comment]
Great. Thank you.

**Comment by tin2tin** [comment]
If you want to update more add-ons to 2.80, this add-on can point out the most common things which needs to be updated: 
https://blenderartists.org/t/how-would-you-show-some-love-for-the-blender-text-editor/1163857/131
