### ISSUE TITLE
request

### ISSUE THREAD

**Issue by mond-cz** [elmopl/ktba#2]
Sorry for opening as issue (for some reason "Pull request" doesn't want me to open new one.
(Or I missed something.)

- One thing that would really help - if script can remember last config.
(rendering is repetitive task ... you know, again and again is something wrong in animation :) )

- Merge parts together
There is another script, you probably know, that is not so under fingers as yours, but he use ffmpeg for merge. https://github.com/mikeycal/the-video-editors-render-script-for-blender

- Ability to set Relative path for output directory

Thanks for your opinion

**Comment by elmopl** [comment]
I think those could be 3 separate issues (easier for tracking).

> One thing that would really help - if script can remember last config.

I need to learn how to do that. There surely is a way to save it in project. #5

> Merge parts together

Sadly that's not something I think Blender can do without depending on external library thus complicating installation a lot. #4

> Ability to set Relative path for output directory

That's the second easiest bit. #3

P.S.  "Pull request" is when you want to submit code changes.

I am closing this one in favour of having 3 separate items.

**Comment by mond-cz** [comment]
Thanks for your attention :)
 "Pull request" - OK :) I thought its some error when site redirect me to code comparison :) Thanks for explanation.
