### ISSUE TITLE
Does it work for 2.90?

### ISSUE THREAD

**Issue by sirdavid32** [elmopl/ktba#29]
Hi. I unpacked the .zip, unpacked the "addon" folder, and re .zip it. Targeted it back in Blender>addons, but it doesn't show the VSE addon to activate it.
I also downloaded the ktba master.zip, installed through addons, but the VSE addon is not listed (I guess it is because it is 2.79 version?)

How do I install this correctly?
Thanks.

**Comment by tin2tin** [comment]
You only need to download and install parallel_render.py and install that: https://raw.githubusercontent.com/elmopl/ktba/master/scripts/addons/parallel_render.py

**Comment by sirdavid32** [comment]
Fantastic! thank you very much! I tested and it works. Drops rendering time by half. I wish it could be faster, but for now (or until the VSE refactor) this is great to work with.

**Comment by elmopl** [comment]
I also just bumped the tests to use 2.91. It looks like no changes in API so it seems to work fine with newer versions of Blender.
