### ISSUE TITLE
Parallel Render Error

### ISSUE THREAD

**Issue by tin2tin** [elmopl/ktba#6]
I'm getting this error on Win 8:
[https://preview.ibb.co/dGYYee/ffmpeg_error.png](https://preview.ibb.co/dGYYee/ffmpeg_error.png)

**Comment by tin2tin** [comment]
I haven't saved a .blend file - doing so - makes it work. So maybe a check, if the project has been saved before running the export, could avoid this error?

Here it sounds like the audio is "jumping" a bit in the resulting file. Is it playing normally for you? 

Anyway, I really like your script - maybe you could post about it in the FB VSE group? https://www.facebook.com/groups/1981104845289453/

**Comment by tin2tin** [comment]
Well, now it seems like there is a permission problem again. Maybe it is better to create a temp folder in Documents and then delete it again after a successful export?

**Comment by elmopl** [comment]
Unfortunately that does not work if you have relative paths in your project (as they will not work if I put file somewhere else). 

I will have a think what to do about it. 

I save temporary file to include in render any unsaved changes in your project. I think I could check if everything is saved and use file directly without creating a temporary one.

**Comment by tin2tin** [comment]
Ah, notice the path to ffmpeg in the ffmpeg command line. The executable is missing, but when entering the path, no error is detected(only if it is a missing file). So it needs to check for ffmpeg.exe. 

Maybe the preferences need to check for the executable and maybe add a button for selecting the path to the executable?

**Comment by elmopl** [comment]
I fixed the fist issue of not noticing that provided path is not actual executable.

I will probably look into making the cleaning up part an option too.

**Comment by tin2tin** [comment]
Great. You probably already know this, here's a bit on checking if the .blend project is saved(if it isn't, it will cause an error as mentioned above): https://blender.stackexchange.com/questions/58711/python-check-if-file-was-saved
